/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nms;

import static connection.connect_database.connection_string;
import static connection.connect_database.database_password;
import static connection.connect_database.database_username;
import static connection.connect_database.driver_name;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author amprojects
 */
public class plants extends javax.swing.JFrame {
int pid=0;
int tpid=0;
    /**
     * Creates new form plants
     */
    public plants() {
        initComponents();
        getid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        plant_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        plant_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        plant_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        plant_month = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        climate = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plant Info NMS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Plants Info");

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Plant ID");

        jLabel3.setText("Plant Name");

        jLabel4.setText("Plant Price");

        jLabel5.setText("Plant Season Months");

        jLabel6.setText("Plant  Climate Condition");

        climate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Summer", "Winter", "Spring" }));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(">>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Close");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(plant_id)
                            .addComponent(jLabel3)
                            .addComponent(plant_name)
                            .addComponent(jLabel4)
                            .addComponent(plant_price)
                            .addComponent(jLabel5)
                            .addComponent(plant_month)
                            .addComponent(jLabel6)
                            .addComponent(climate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(climate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        plant_id.setText("");
        plant_name.setText("");
        plant_price.setText("");
        plant_month.setText("");
        climate.removeAllItems();
        climate.addItem("Summer");
        climate.addItem("Winter");
        climate.addItem("Spring");
        getid();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
    {
        if(plant_id.getText().equals(""))
        {
           jOptionPane1.showMessageDialog(null,"Plant ID not set"); 
        }
        else if(plant_name.getText().equals(""))
        {
            jOptionPane1.showMessageDialog(null,"Please enter plant name");
        }
        else if(plant_price.getText().equals(""))
        {
            jOptionPane1.showMessageDialog(null,"Please enter plant price");
        }
        else if(plant_month.getText().equals(""))
        {
            jOptionPane1.showMessageDialog(null,"Please enter plant season in months");
        }
        else
        {
        
            Class.forName(driver_name);
            Connection con=DriverManager.getConnection(connection_string,database_username,database_password);
            PreparedStatement pst=con.prepareStatement("insert into plants values("+plant_id.getText()+",'"+plant_name.getText()+"','"+plant_price.getText()+"','"+plant_month.getText()+"','"+climate.getSelectedItem()+"')");
            int i=pst.executeUpdate();
            if(i>0)
            {
                jOptionPane1.showMessageDialog(null,"Record insert successfully");
                clear_data();
            }
            else
            {
               jOptionPane1.showMessageDialog(null,"Record not insert tyr later"); 
               
            }
        }
    }
    catch(Exception ex)
    {
        jOptionPane1.showMessageDialog(null,ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(plant_id.getText().equals(""))
            {
                jOptionPane1.showMessageDialog(null,"Plant ID not available !");
            }
            else
            {
            Class.forName(driver_name);
            Connection con=DriverManager.getConnection(connection_string,database_username,database_password);
            PreparedStatement pst=con.prepareStatement("delete from plants where plant_id="+plant_id.getText()+"");
            int i=pst.executeUpdate();
            if(i>0)
            {
                jOptionPane1.showMessageDialog(null,"Record delete successfully  !");
                clear_data();
            }
            else
            {
                jOptionPane1.showMessageDialog(null,"Record delete failed try later !");
            }
            }
        }
        catch(Exception ex)
        {
          jOptionPane1.showMessageDialog(null,ex);  
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver_name);
            Connection con=DriverManager.getConnection(connection_string,database_username,database_password);
            PreparedStatement pst=con.prepareStatement("select * from plants where plant_id="+search.getText()+"");
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                plant_id.setText(String.valueOf(rs.getInt(1)));
                plant_name.setText(rs.getString(2));
                plant_price.setText(rs.getString(3));
                plant_month.setText(rs.getString(4));
                climate.removeAllItems();
                climate.addItem(rs.getString(5));
                
                climate.addItem("Summer");
                climate.addItem("Winter");
                climate.addItem("Spring");
            }
            else
            {
                 jOptionPane1.showMessageDialog(null,"No record found !");
            }
        }
        catch(Exception ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(plant_id.getText().equals(""))
            {
                 jOptionPane1.showMessageDialog(null,"Plant ID not available !");
            }
            else
            {
            Class.forName(driver_name);
            Connection con=DriverManager.getConnection(connection_string,database_username,database_password);
            PreparedStatement pst=con.prepareStatement("update plants set plant_name='"+plant_name.getText()+"',plant_price='"+plant_price.getText()+"',season_months='"+plant_month.getText()+"',climate_condition='"+climate.getSelectedItem()+"' where plant_id="+plant_id.getText()+"");
            int i=pst.executeUpdate();
            if(i>0)
            {
                jOptionPane1.showMessageDialog(null,"Record update successfully");
            }
            else
            {
                jOptionPane1.showMessageDialog(null,"Record not update");
            }
            }
        }
        catch(Exception ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try
        {
            tpid=tpid+1;
            Class.forName(driver_name);
            Connection con=DriverManager.getConnection(connection_string,database_username,database_password);
            PreparedStatement pst=con.prepareStatement("select * from plants where plant_id="+tpid+"");
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                plant_id.setText(String.valueOf(rs.getInt(1)));
                plant_name.setText(rs.getString(2));
                plant_price.setText(rs.getString(3));
                plant_month.setText(rs.getString(4));
                climate.removeAllItems();
                climate.addItem(rs.getString(5));
                
                climate.addItem("Summer");
                climate.addItem("Winter");
                climate.addItem("Spring");
            }
            else
            {
                 jOptionPane1.showMessageDialog(null,"No next record found !");
                 tpid=tpid-1;
            }
        }
        catch(Exception ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(tpid>0)
            {
            tpid=tpid-1;
            }
            Class.forName(driver_name);
            Connection con=DriverManager.getConnection(connection_string,database_username,database_password);
            PreparedStatement pst=con.prepareStatement("select * from plants where plant_id="+tpid+"");
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                plant_id.setText(String.valueOf(rs.getInt(1)));
                plant_name.setText(rs.getString(2));
                plant_price.setText(rs.getString(3));
                plant_month.setText(rs.getString(4));
                climate.removeAllItems();
                climate.addItem(rs.getString(5));
                
                climate.addItem("Summer");
                climate.addItem("Winter");
                climate.addItem("Spring");
            }
            else
            {
                 jOptionPane1.showMessageDialog(null,"No previous record found !");
            }
        }
        catch(Exception ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
public void getid()
{
    try
    {
       pid=0;
       Class.forName(driver_name);
       Connection con=DriverManager.getConnection(connection_string,database_username,database_password);
       PreparedStatement pst=con.prepareStatement("select * from plants");
       ResultSet rs=pst.executeQuery();
       while(rs.next())
       {
           pid=rs.getInt(1);
       }
       pid=pid+1;
       plant_id.setText(String.valueOf(pid));
    }
    catch(Exception ex)
    {
        jOptionPane1.showMessageDialog(null,ex);
    }
}
public void clear_data()
{
        plant_id.setText("");
        plant_name.setText("");
        plant_price.setText("");
        plant_month.setText("");
        getid();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox climate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField plant_id;
    private javax.swing.JTextField plant_month;
    private javax.swing.JTextField plant_name;
    private javax.swing.JTextField plant_price;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
